name: Build & publish new release

on:
  release:
    types: [released]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.6

      - name: Install build & twine
        run: python -m pip install build twine

      - name: Build
        run: python -m build

      - name: Upload
        run: |
          twine upload \
            --repository-url https://test.pypi.org/legacy/ \
            --username __token__ \
            --password "${{ secrets.PYPI_TOKEN }}" \
            dist/*
